version: "3.2"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./docker/pg-data:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
      POSTGRES_DB: bank
    networks:
      - data_net
    ports:
      - "5432:5432"

networks:
  data_net:
    driver: bridge