"""Initial migration.

Revision ID: 463f42c0cbcd
Revises: 
Create Date: 2023-06-13 21:03:00.926864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463f42c0cbcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bc_identify', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('current', 'saving', name='account_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bc_identify', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('id_gov', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of', sa.Enum('credit', 'charge', name='transaction_type'), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('person')
    op.drop_table('agency')
    op.drop_table('account')
    # ### end Alembic commands ###
