"""Add foreignkey account

Revision ID: 8ec0fd413f27
Revises: 463f42c0cbcd
Create Date: 2023-06-13 21:41:21.031799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec0fd413f27'
down_revision = '463f42c0cbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_owner', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('agency_owner', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'agency', ['agency_owner'], ['id'])
        batch_op.create_foreign_key(None, 'person', ['person_owner'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agency_owner')
        batch_op.drop_column('person_owner')

    # ### end Alembic commands ###
